import type {
  Culture,
  StockItem,
  Commande,
  Fournisseur,
  Employe,
  Parcelle,
  Lot,
  NonConformite,
  Actif,
  Assurance,
} from "./types";

export const cultures: Culture[] = [
  {
    id: "cul-001",
    nom: "Maïs Hybride DK8031",
    parcelle: "P-A1",
    surface: 45,
    stade: "Croissance",
    dateDebut: "2025-03-15",
    dateFin: "2025-07-20",
    progress: 52,
    rendementPrevu: 6.5,
    statut: "Active",
    operateur: "Brou Emmanuel",
  },
  {
    id: "cul-002",
    nom: "Cacao Forastero",
    parcelle: "P-B3",
    surface: 120,
    stade: "Floraison",
    dateDebut: "2024-10-01",
    dateFin: "2025-09-30",
    progress: 70,
    rendementPrevu: 2.8,
    statut: "Active",
    operateur: "Traoré Aminata",
  },
  {
    id: "cul-003",
    nom: "Manioc TME 419",
    parcelle: "P-C2",
    surface: 30,
    stade: "Récolte",
    dateDebut: "2025-01-10",
    dateFin: "2025-06-30",
    progress: 90,
    rendementPrevu: 18.0,
    statut: "Active",
    operateur: "Dembélé Ladji",
  },
  {
    id: "cul-004",
    nom: "Riz Nérica 4",
    parcelle: "P-D1",
    surface: 55,
    stade: "Semis",
    dateDebut: "2025-05-20",
    dateFin: "2025-10-15",
    progress: 10,
    rendementPrevu: 4.2,
    statut: "Active",
    operateur: "Dembélé Ladji",
  },
  {
    id: "cul-005",
    nom: "Plantain Batard",
    parcelle: "P-E4",
    surface: 25,
    stade: "Post-récolte",
    dateDebut: "2024-06-01",
    dateFin: "2025-03-31",
    progress: 100,
    rendementPrevu: 12.0,
    rendementReel: 11.4,
    statut: "Terminée",
    operateur: "Brou Emmanuel",
  },
];

export const stocks: StockItem[] = [
  {
    id: "stk-001",
    produit: "Engrais NPK 20-10-10",
    categorie: "Intrants",
    quantite: 3200,
    unite: "kg",
    seuilCritique: 500,
    entrepot: "Entrepôt A - Yamoussoukro",
    valeur: 4800000,
    fournisseur: "IVOIRE ENGRAIS SARL",
  },
  {
    id: "stk-002",
    produit: "Herbicide Glyphosate 360",
    categorie: "Intrants",
    quantite: 180,
    unite: "L",
    seuilCritique: 50,
    entrepot: "Entrepôt A - Yamoussoukro",
    valeur: 540000,
    datePeremption: "2026-03-01",
    fournisseur: "AGRO-CHIMIE CI",
  },
  {
    id: "stk-003",
    produit: "Semences Maïs DK8031",
    categorie: "Intrants",
    quantite: 420,
    unite: "kg",
    seuilCritique: 100,
    entrepot: "Entrepôt B - Bouaké",
    valeur: 1260000,
    datePeremption: "2026-01-15",
    fournisseur: "SEMENCES AFRICA",
  },
  {
    id: "stk-004",
    produit: "Maïs séché (récolte)",
    categorie: "Production",
    quantite: 28500,
    unite: "kg",
    seuilCritique: 1000,
    entrepot: "Silo Principal - Yamoussoukro",
    valeur: 14250000,
  },
  {
    id: "stk-005",
    produit: "Cacao fèves sèches",
    categorie: "Production",
    quantite: 12400,
    unite: "kg",
    seuilCritique: 500,
    entrepot: "Entrepôt C - San-Pédro",
    valeur: 49600000,
  },
  {
    id: "stk-006",
    produit: "Gasoil agricole",
    categorie: "Intrants",
    quantite: 2200,
    unite: "L",
    seuilCritique: 400,
    entrepot: "Entrepôt A - Yamoussoukro",
    valeur: 2860000,
    fournisseur: "TOTAL ENERGIES CI",
  },
  {
    id: "stk-007",
    produit: "Insecticide Pyréthrine",
    categorie: "Intrants",
    quantite: 42,
    unite: "L",
    seuilCritique: 30,
    entrepot: "Entrepôt B - Bouaké",
    valeur: 336000,
    datePeremption: "2025-12-31",
    fournisseur: "AGRO-CHIMIE CI",
  },
];

export const commandes: Commande[] = [
  {
    id: "cmd-001",
    type: "Vente",
    partenaire: "SOCOLAIT Abidjan",
    produit: "Maïs séché",
    quantite: 5000,
    prixUnitaire: 520,
    total: 2600000,
    statut: "En cours",
    dateCommande: "2025-05-28",
    dateLivraison: "2025-06-10",
    devise: "XOF",
  },
  {
    id: "cmd-002",
    type: "Vente",
    partenaire: "NESTLE Côte d'Ivoire",
    produit: "Cacao fèves sèches",
    quantite: 3000,
    prixUnitaire: 4200,
    total: 12600000,
    statut: "Confirmée",
    dateCommande: "2025-05-30",
    dateLivraison: "2025-06-20",
    devise: "XOF",
  },
  {
    id: "cmd-003",
    type: "Vente",
    partenaire: "Groupe CDCI",
    produit: "Manioc frais",
    quantite: 8000,
    prixUnitaire: 150,
    total: 1200000,
    statut: "En attente",
    dateCommande: "2025-06-02",
    dateLivraison: "2025-06-15",
    devise: "XOF",
  },
  {
    id: "cmd-004",
    type: "Vente",
    partenaire: "SIPRA Industries",
    produit: "Maïs séché",
    quantite: 10000,
    prixUnitaire: 510,
    total: 5100000,
    statut: "Livrée",
    dateCommande: "2025-05-10",
    dateLivraison: "2025-05-25",
    devise: "XOF",
  },
  {
    id: "cmd-005",
    type: "Vente",
    partenaire: "Export Barry Callebaut",
    produit: "Cacao fèves sèches",
    quantite: 8000,
    prixUnitaire: 4350,
    total: 34800000,
    statut: "Confirmée",
    dateCommande: "2025-06-01",
    dateLivraison: "2025-07-05",
    incoterm: "FOB",
    devise: "USD",
  },
  {
    id: "cmd-006",
    type: "Vente",
    partenaire: "Marché de Gros Bouaké",
    produit: "Plantain régimes",
    quantite: 2000,
    prixUnitaire: 300,
    total: 600000,
    statut: "Annulée",
    dateCommande: "2025-05-18",
    dateLivraison: "2025-05-28",
    devise: "XOF",
  },
];

export const fournisseurs: Fournisseur[] = [
  {
    id: "fou-001",
    nom: "AGRO-CHIMIE CI",
    contact: "Konan Yves",
    telephone: "+225 07 12 34 56",
    email: "yves@agrochimie-ci.com",
    adresse: "Zone Industrielle de Yopougon, Abidjan",
    categorie: "Produits phytosanitaires",
    statut: "Actif",
  },
  {
    id: "fou-002",
    nom: "SEMENCES AFRICA",
    contact: "Diallo Moussa",
    telephone: "+225 05 78 90 12",
    email: "m.diallo@semencesafrica.com",
    adresse: "Rue du Commerce, Bouaké",
    categorie: "Semences",
    statut: "Actif",
  },
  {
    id: "fou-003",
    nom: "TOTAL ENERGIES CI",
    contact: "Esso Jean-Marc",
    telephone: "+225 27 20 50 50",
    email: "jm.esso@totalenergies.ci",
    adresse: "Boulevard Valéry Giscard d'Estaing, Abidjan",
    categorie: "Carburant",
    statut: "Actif",
  },
  {
    id: "fou-004",
    nom: "IVOIRE ENGRAIS SARL",
    contact: "N'Goran Ama",
    telephone: "+225 01 23 45 67",
    email: "contact@ivoire-engrais.ci",
    adresse: "PK 24 Route de Dabou, Abidjan",
    categorie: "Intrants",
    statut: "Actif",
  },
  {
    id: "fou-005",
    nom: "MATÉRIEL AGRI-OUEST",
    contact: "Coulibaly Ibrahim",
    telephone: "+225 06 55 44 33",
    email: "i.coulibaly@materielagriouest.ci",
    adresse: "Carrefour Dimbokro, Man",
    categorie: "Équipements",
    statut: "Inactif",
  },
];

export const employes: Employe[] = [
  {
    id: "emp-001",
    nom: "Koffi",
    prenom: "Jean-Baptiste",
    poste: "Directeur Général",
    typeContrat: "CDI",
    salaireBase: 850000,
    dateEmbauche: "2018-01-15",
    telephone: "+225 07 00 11 22",
    email: "jb.koffi@agrifrik.ci",
    actif: true,
    formations: ["Management agricole", "Finance d'entreprise"],
  },
  {
    id: "emp-002",
    nom: "Traoré",
    prenom: "Aminata",
    poste: "Responsable Agronomie",
    typeContrat: "CDI",
    salaireBase: 520000,
    dateEmbauche: "2019-03-01",
    telephone: "+225 05 33 44 55",
    email: "a.traore@agrifrik.ci",
    actif: true,
    zone: "Yamoussoukro",
    formations: ["Agronomie tropicale", "Certification UTZ"],
  },
  {
    id: "emp-003",
    nom: "Brou",
    prenom: "Emmanuel",
    poste: "Chef de Parcelle",
    typeContrat: "CDI",
    salaireBase: 280000,
    dateEmbauche: "2020-06-15",
    telephone: "+225 01 66 77 88",
    actif: true,
    zone: "Yamoussoukro",
  },
  {
    id: "emp-004",
    nom: "Ouattara",
    prenom: "Fatoumata",
    poste: "Comptable",
    typeContrat: "CDI",
    salaireBase: 350000,
    dateEmbauche: "2021-01-10",
    telephone: "+225 07 99 00 11",
    email: "f.ouattara@agrifrik.ci",
    actif: true,
    formations: ["SYSCOHADA révisé"],
  },
  {
    id: "emp-005",
    nom: "Koné",
    prenom: "Seydou",
    poste: "Responsable Logistique",
    typeContrat: "CDI",
    salaireBase: 380000,
    dateEmbauche: "2020-09-01",
    telephone: "+225 05 22 33 44",
    actif: false,
    zone: "San-Pédro",
  },
  {
    id: "emp-006",
    nom: "Aké",
    prenom: "Marie-Claire",
    poste: "Commercial Export",
    typeContrat: "CDI",
    salaireBase: 310000,
    dateEmbauche: "2022-04-01",
    telephone: "+225 01 55 66 77",
    email: "mc.ake@agrifrik.ci",
    actif: true,
    formations: ["Incoterms 2020", "Commerce international"],
  },
  {
    id: "emp-007",
    nom: "Dembélé",
    prenom: "Ladji",
    poste: "Technicien Agricole",
    typeContrat: "CDD",
    salaireBase: 210000,
    dateEmbauche: "2023-02-15",
    telephone: "+225 07 88 99 00",
    actif: true,
    zone: "Bouaké",
  },
];

// ====== PARCELLES ======

export const mockParcelles: Parcelle[] = [
  {
    id: "par-001",
    code: "P-A1",
    localite: "Yamoussoukro - Zone Nord",
    culture: "Maïs Hybride DK8031",
    surface: 45,
    sol: "Limon argileux",
    propriete: "Propriété",
    gpsLat: 6.8276,
    gpsLng: -5.2893,
    statut: "Active",
    certifiee: false,
  },
  {
    id: "par-002",
    code: "P-B3",
    localite: "Soubré - Bas-Sassandra",
    culture: "Cacao Forastero",
    surface: 120,
    sol: "Ferralitique rouge",
    propriete: "Propriété",
    gpsLat: 5.7880,
    gpsLng: -6.5993,
    statut: "Active",
    certifiee: true,
  },
  {
    id: "par-003",
    code: "P-C2",
    localite: "Bouaké - Périmètre Est",
    culture: "Manioc TME 419",
    surface: 30,
    sol: "Sablo-limoneux",
    propriete: "Fermage",
    gpsLat: 7.6939,
    gpsLng: -5.0300,
    statut: "En récolte",
    certifiee: false,
  },
  {
    id: "par-004",
    code: "P-D1",
    localite: "Korhogo - Plaine irriguée",
    culture: "Riz Nérica 4",
    surface: 55,
    sol: "Argile lourde",
    propriete: "Fermage",
    gpsLat: 9.4580,
    gpsLng: -5.6294,
    statut: "Active",
    certifiee: false,
  },
  {
    id: "par-005",
    code: "P-E4",
    localite: "Abengourou - Zone Plantain",
    culture: "Plantain Batard",
    surface: 25,
    sol: "Limon rouge",
    propriete: "Propriété",
    gpsLat: 6.7293,
    gpsLng: -3.4961,
    statut: "En repos",
    certifiee: false,
  },
  {
    id: "par-006",
    code: "P-F2",
    localite: "San-Pédro - Corridor cacao",
    culture: "Cacao Forastero",
    surface: 80,
    sol: "Ferralitique brun",
    propriete: "Propriété",
    gpsLat: 4.7485,
    gpsLng: -6.6363,
    statut: "Vide",
    certifiee: true,
  },
];

// ====== LOTS ======

export const mockLots: Lot[] = [
  {
    id: "lot-001",
    numero: "LOT-2025-CAC-001",
    produit: "Cacao fèves",
    quantiteEntree: 4200,
    quantiteSortie: 3800,
    parcelle: "P-B3",
    operateur: "Traoré Aminata",
    dateRecolte: "2025-04-10",
    dateFermentation: "2025-04-12",
    dateSechage: "2025-04-19",
    grade: "Grade 1",
    certificatQualite: "CERT-2025-041",
    statut: "Export",
    destination: "Barry Callebaut - Amsterdam",
  },
  {
    id: "lot-002",
    numero: "LOT-2025-CAC-002",
    produit: "Cacao fèves",
    quantiteEntree: 3100,
    parcelle: "P-F2",
    operateur: "Brou Emmanuel",
    dateRecolte: "2025-05-05",
    dateFermentation: "2025-05-07",
    dateSechage: "2025-05-14",
    grade: "Grade 2",
    statut: "Stockage",
  },
  {
    id: "lot-003",
    numero: "LOT-2025-MAI-001",
    produit: "Maïs séché",
    quantiteEntree: 28500,
    quantiteSortie: 15000,
    parcelle: "P-A1",
    operateur: "Dembélé Ladji",
    dateRecolte: "2025-05-20",
    statut: "Stockage",
    destination: "SOCOLAIT / SIPRA",
  },
  {
    id: "lot-004",
    numero: "LOT-2025-MAN-001",
    produit: "Manioc frais",
    quantiteEntree: 9000,
    parcelle: "P-C2",
    operateur: "Brou Emmanuel",
    dateRecolte: "2025-06-01",
    statut: "Contrôle",
  },
  {
    id: "lot-005",
    numero: "LOT-2025-CAC-003",
    produit: "Cacao fèves",
    quantiteEntree: 1800,
    parcelle: "P-B3",
    operateur: "Traoré Aminata",
    dateRecolte: "2025-06-10",
    dateFermentation: "2025-06-12",
    statut: "Fermentation",
  },
];

// ====== NON-CONFORMITÉS ======

export const mockNonConformites: NonConformite[] = [
  {
    id: "nc-001",
    date: "2025-04-22",
    description: "Taux d'humidité des fèves de cacao supérieur à 8% (mesuré à 9.4%) au lot LOT-2025-CAC-001",
    criticite: "Majeure",
    responsable: "Traoré Aminata",
    echeance: "2025-05-05",
    statut: "Clôturée",
    actionCorrective: "Prolongation du séchage solaire de 3 jours. Contrôle de l'hygromètre de l'entrepôt C.",
  },
  {
    id: "nc-002",
    date: "2025-05-10",
    description: "Étiquetage non conforme sur 12 sacs de maïs — absence du numéro de lot et de la date de récolte",
    criticite: "Mineure",
    responsable: "Koné Seydou",
    echeance: "2025-05-20",
    statut: "Clôturée",
    actionCorrective: "Réétiquetage complet du lot. Mise à jour de la procédure d'emballage PRC-012.",
  },
  {
    id: "nc-003",
    date: "2025-05-28",
    description: "Présence de corps étrangers (pierres) détectée lors du tri du lot LOT-2025-CAC-002 — 3 sacs concernés",
    criticite: "Critique",
    responsable: "Brou Emmanuel",
    echeance: "2025-06-05",
    statut: "En traitement",
    actionCorrective: "Isolation des 3 sacs, re-tri manuel en cours. Audit du processus de récolte P-F2 programmé.",
  },
  {
    id: "nc-004",
    date: "2025-06-08",
    description: "Stock d'insecticide Pyréthrine en dessous du seuil critique sans déclenchement d'alerte d'approvisionnement",
    criticite: "Mineure",
    responsable: "Ouattara Fatoumata",
    echeance: "2025-06-20",
    statut: "Ouverte",
  },
];

// ====== ACTIFS IMMOBILISÉS ======

export const mockActifs: Actif[] = [
  {
    id: "act-001",
    code: "VEH-001",
    designation: "Tracteur John Deere 5075E",
    dateAcquisition: "2021-03-10",
    valeurBrute: 18500000,
    dureeVie: 10,
    tauxAmortissement: 10,
    amortissementCumule: 7400000,
    valeurNette: 11100000,
    statut: "Actif",
    categorie: "Véhicule",
  },
  {
    id: "act-002",
    code: "BAT-001",
    designation: "Hangar de stockage - Yamoussoukro",
    dateAcquisition: "2019-06-01",
    valeurBrute: 35000000,
    dureeVie: 20,
    tauxAmortissement: 5,
    amortissementCumule: 10500000,
    valeurNette: 24500000,
    statut: "Actif",
    categorie: "Bâtiment",
  },
  {
    id: "act-003",
    code: "EQP-001",
    designation: "Station de séchage solaire modulaire",
    dateAcquisition: "2022-01-15",
    valeurBrute: 8200000,
    dureeVie: 8,
    tauxAmortissement: 12.5,
    amortissementCumule: 3075000,
    valeurNette: 5125000,
    statut: "Actif",
    categorie: "Équipement",
  },
  {
    id: "act-004",
    code: "VEH-002",
    designation: "Camion Iveco Daily 35C15 — Frigo",
    dateAcquisition: "2020-09-20",
    valeurBrute: 14000000,
    dureeVie: 8,
    tauxAmortissement: 12.5,
    amortissementCumule: 8750000,
    valeurNette: 5250000,
    statut: "En maintenance",
    categorie: "Véhicule",
  },
  {
    id: "act-005",
    code: "MAT-001",
    designation: "Groupe électrogène Perkins 50 kVA",
    dateAcquisition: "2018-11-05",
    valeurBrute: 6500000,
    dureeVie: 7,
    tauxAmortissement: 14.29,
    amortissementCumule: 6500000,
    valeurNette: 0,
    statut: "Totalement amorti",
    categorie: "Matériel",
  },
];

// ====== ASSURANCES ======

export const mockAssurances: Assurance[] = [
  {
    id: "ass-001",
    numeroPolice: "POL-NSIA-2024-00812",
    assureur: "NSIA Assurances CI",
    type: "Assurance récolte multirisques",
    objetAssure: "Cultures Maïs, Manioc, Riz — campagne 2025",
    valeurAssuree: 45000000,
    primeAnnuelle: 1350000,
    franchise: 10,
    dateDebut: "2025-01-01",
    dateFin: "2025-12-31",
    statut: "Active",
  },
  {
    id: "ass-002",
    numeroPolice: "POL-SAHAM-2023-05541",
    assureur: "Saham Assurance",
    type: "Assurance flotte automobile",
    objetAssure: "Tracteur JD5075E + Camion Iveco Daily Frigo",
    valeurAssuree: 32500000,
    primeAnnuelle: 975000,
    franchise: 5,
    dateDebut: "2024-09-01",
    dateFin: "2025-08-31",
    statut: "Renouvellement",
  },
  {
    id: "ass-003",
    numeroPolice: "POL-SUNU-2024-10023",
    assureur: "SUNU Assurances",
    type: "Assurance incendie & bris de machine",
    objetAssure: "Hangar Yamoussoukro + Équipements production",
    valeurAssuree: 60000000,
    primeAnnuelle: 720000,
    franchise: 15,
    dateDebut: "2024-06-15",
    dateFin: "2025-06-14",
    statut: "Expirée",
  },
  {
    id: "ass-004",
    numeroPolice: "POL-ALLIANZ-2025-00234",
    assureur: "Allianz CI",
    type: "Assurance responsabilité civile exploitation",
    objetAssure: "Ensemble de l'exploitation AGRIFRIK",
    valeurAssuree: 100000000,
    primeAnnuelle: 480000,
    franchise: 0,
    dateDebut: "2025-03-01",
    dateFin: "2026-02-28",
    statut: "Active",
  },
];
